### ISSUE TITLE
Text is on top of each other if no background color is set on page

### ISSUE THREAD

**Issue by RichardLindhout** [computerjazz/react-native-infinite-pager#4] opened 2022-06-10 16:35 UTC
Example without background color results first render with things on top of each other. If you do some gesture on it it fixes itself. If you have white background the bug is not visible anymore. 

<img width="403" alt="Schermafbeelding 2022-06-10 om 18 34 57" src="https://user-images.githubusercontent.com/6492229/173111599-7790b834-8d8f-42ea-a529-2f72b114a75f.png">

<img width="409" alt="Schermafbeelding 2022-06-10 om 18 35 03" src="https://user-images.githubusercontent.com/6492229/173111607-3a120a91-2cd6-4a3f-b22a-7d2d15e76dd0.png">

**Comment by computerjazz** [comment] 2022-06-11 15:41
What version are you using?  There was a fix for this in 0.0.12.
Also, what version of reanimated?

**Comment by wbercx** [comment] 2022-07-24 12:01
So using `0.0.12` and Reanimated `2.2.3`, I do briefly see overlapping pages on the initial render. Giving the pages a background color makes it so that it briefly shows page 1 before correcting to page 0, which is still a bit jarring.

Below is admittedly an absolute hackjob, but works because `focusAnim` currently shortcircuits to `99999` when there is no pageWidth. This gives page 0 priority and makes the others initially invisible.

````diff
    const animStyle = useAnimatedStyle(() => {
-      // Short circuit page interpolation to prevent buggy initial values due to possible race condition:
-      // https://github.com/software-mansion/react-native-reanimated/issues/2571
-     if (!pageWidth.value) return {};
      return pageInterpolatorRef.current({
        focusAnim,
        pageAnim,
-       pageWidth,
+       pageWidth: (index !== 0 && !pageWidth.value) ? focusAnim : pageWidth,
        index,
      });
    }, [pageWidth, pageAnim, index, translation]);
````

**Comment by computerjazz** [comment] 2022-07-24 21:26
your "hackjob" works great @wbercx , thanks! Released in https://github.com/computerjazz/react-native-infinite-pager/releases/tag/v0.1.0

**Closed** 2022-07-27 05:15 UTC

**Comment by nicolaosm** [comment] 2024-03-11 20:10
Why was this "hackjob" removed in newer commits and releases? The issue is happening on my end now...

**Comment by nicolaosm** [comment] 2024-03-20 11:21
Any idea about what happened to the fix @computerjazz ? It doesn't to be there anymore and im getting this issue on slow devices. Thanks

**Comment by computerjazz** [comment] 2024-03-23 17:34
@nicolaosm just pushed a fix,  try again with latest?
